version: "3.3"
services:
  r-container:
    image: r-base:4.4.3
    container_name: "r-container"
    working_dir: /mnt
    volumes:
      - ./solution:/mnt
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
